disabled_rules:
  - trailing_whitespace
  - nesting
  - variable_name

opt_in_rules:
  - empty_count
  - missing_docs

excluded:
  - Pods
  - Examples/Basic/Pods
  - Examples/Intermediate/Pods

line_length: 150
